apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms
    spec:
      containers:
        - image: southamerica-west1-docker.pkg.dev/microservices-nest-dev/register-nest-dev/nest-microservices-products:1.0.0
          name: nest-microservices-products
          env:
            - name: NATS_SERVER
              value: nats://nats-server
            - name: PORT
              value: '3000'
            - name: DATABASE_URL
              value: file:./dev.db
          resources: {}
      imagePullSecrets:
        - name: gcr-json-key
status: {}
