name: nest-microservices

services:
  nats-server:
    restart: unless-stopped
    container_name: nats-server
    image: nats:latest

  client-gateway:
    restart: unless-stopped
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    environment:
      - NATS_SERVER=${NATS_SERVER}
      - PORT=${GATEWAY_PORT}
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'

  orders-ms:
    restart: unless-stopped
    container_name: orders-ms
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    environment:
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVER=${NATS_SERVER}
      - PORT=${ORDERS_PORT}

  products-ms:
    restart: unless-stopped
    container_name: products-ms
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}
      - NATS_SERVER=${NATS_SERVER}
      - PORT=${PRODUCTS_PORT}

  payments-ms:
    restart: unless-stopped
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - '${PAYMENTS_PORT}:${PAYMENTS_PORT}'
    environment:
      - PORT=${PAYMENTS_PORT}
      - STRIPE_API_KEY=${PAYMENTS_STRIPE_API_KEY}
      - SUCCESS_URL=${PAYMENTS_SUCCESS_URL}
      - CANCEL_URL=${PAYMENTS_CANCEL_URL}
      - ENDPOINT_SECRET=${PAYMENTS_ENDPOINT_SECRET}
      - NATS_SERVER=${NATS_SERVER}

  auth-ms:
    restart: unless-stopped
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=${AUTH_PORT}
      - NATS_SERVER=${NATS_SERVER}
      - DATABASE_URL=${AUTH_DATABASE_URL}

volumes:
  orders-db-volume:
