apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-ms
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-ms
    spec:
      containers:
        - image: southamerica-west1-docker.pkg.dev/microservices-nest-dev/register-nest-dev/nest-microservices-orders:1.0.0
          name: nest-microservices-orders
          env:
            - name: PORT
              value: '3000'
            - name: NATS_SERVER
              value: nats://nats-server
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: DATABASE_URL
          resources: {}
      imagePullSecrets:
        - name: gcr-json-key
status: {}
